version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/gamingBoxd_db
    depends_on:
      - db
    ports:
      - "3001:3001"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: gamingBoxd_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
